defmodule ExBitmex.Instrument do
  alias __MODULE__

  @type t :: %Instrument{}

  defstruct ~w(
    taker_fee
    turnover24h
    fair_price
    capped
    reference_symbol
    relist_interval
    turnover
    listing
    fair_basis_rate
    limit_up_price
    has_liquidity
    last_price_protected
    funding_base_symbol
    bankrupt_limit_up_price
    funding_interval
    high_price
    option_strike_price
    expiry
    indicative_settle_price
    impact_ask_price
    opening_timestamp
    front
    settl_currency
    open_interest
    funding_rate
    publish_time
    prev_price24h
    limit_down_price
    last_tick_direction
    foreign_notional24h
    max_price
    sell_leg
    inverse_leg
    position_currency
    fair_method
    quote_currency
    home_notional24h
    funding_premium_symbol
    total_turnover
    mid_price
    option_underlying_price
    bankrupt_limit_down_price
    underlying
    maker_fee
    total_volume
    mark_price
    timestamp
    risk_step
    init_margin
    calc_interval
    underlying_symbol
    option_strike_pcnt
    prev_total_volume
    state
    ask_price
    rebalance_timestamp
    settle
    prev_total_turnover
    deleverage
    volume
    impact_mid_price
    limit
    buy_leg
    vwap
    low_price
    prev_close_price
    typ
    underlying_to_settle_multiplier
    impact_bid_price
    funding_timestamp
    publish_interval
    volume24h
    closing_timestamp
    underlying_to_position_multiplier
    option_multiplier
    session_interval
    multiplier
    settled_price
    mark_method
    rebalance_interval
    open_value
    symbol
    indicative_funding_rate
    quote_to_settle_multiplier
    fair_basis
    option_strike_round
    tick_size
    maint_margin
    root_symbol
    settlement_fee
    reference
    funding_quote_symbol
    last_price
    max_order_qty
    is_inverse
    last_change_pcnt
    taxed
    insurance_fee
    indicative_tax_rate
    bid_price
    lot_size
    risk_limit
    is_quanto
  )a
end
